global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'pdf-processor'

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # PDF Processor Application Metrics
  - job_name: 'pdf-processor'
    static_configs:
      - targets: ['localhost:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    
  # Node Exporter for System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s
    
  # Docker Container Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
    scrape_interval: 30s

  # PDF Processor SQS Worker
  - job_name: 'sqs-worker'
    static_configs:
      - targets: ['localhost:8001']
    scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
