global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # PDF Processor metrics
  - job_name: 'pdf-processor'
    static_configs:
      - targets: ['localhost:8001']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Application metrics
  - job_name: 'application'
    static_configs:
      - targets: ['localhost:8001']
    scrape_interval: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
