groups:
  - name: pdf_processing_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(pdf_files_processed_total{status="error"}[5m]) / rate(pdf_files_processed_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate in PDF processing"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes"

      - alert: SlowProcessing
        expr: pdf_processing_duration_seconds{quantile="0.95"} > 120
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Slow PDF processing detected"
          description: "95th percentile processing time is {{ $value }}s"

      - alert: QueueBacklog
        expr: sqs_messages_in_queue > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Large queue backlog"
          description: "{{ $value }} messages in queue"

      - alert: HighCPUUsage
        expr: system_cpu_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      - alert: HighMemoryUsage
        expr: system_memory_percent > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}%"

      - alert: HighDiskUsage
        expr: system_disk_percent > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High disk usage"
          description: "Disk usage is {{ $value }}%"

      - alert: KBSyncFailure
        expr: rate(kb_sync_total{status="failure"}[5m]) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Knowledge Base sync failures"
          description: "KB sync failures detected in the last 5 minutes"

  - name: infrastructure_alerts
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "{{ $labels.job }} service is down"
